---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: flush_handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

    - name: Create folder for Vector
      become: true
      file:
        state: directory
        path: "/opt/vector"
        mode: 0755
    - name: Clear directory
      become: true
      shell: |
        rm -fR /tmp/*
        rm -fR ~/click*
        rm -fR ~/vector*
        rm -fR /opt/vector/*
    - name: Download Vector achive version {{ vector_version }}
      become: true
      ansible.builtin.get_url: 
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "~/"
        mode: 0755
    - name: Extract vector and start
      become: true
      unarchive:
          copy: false
          src: "~/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
          dest: "/opt/vector"
          extra_opts: [--strip-components=2]
          mode: 0755
    - name: Set environment vector
      become: true
      template:
          src: templates/vec.sh.j2
          dest: /etc/profile.d/vec.sh
    - name: Start Vector
      become: true
      shell: |
        echo -e "[Service]\n \
        ExecStart=/opt/vector/bin/vector --config /opt/vector/config/vector.toml\n \
        Restart=always" > /etc/systemd/system/vector.service
        systemctl daemon-reload
        systemctl start vector.service


