---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: 'Check Version'
      command: /opt/vector/bin/vector --version
      register: version
    - name: 'Print version'
      debug:
        msg: "vector version : {{ version.stdout }}"
    - name: 'Run test'
      command: /opt/vector/bin/vector validate /opt/vector/config/vector.toml
      register: test
    - name: 'Print test '
      debug:
        msg: "test : {{ test.stdout }}"
      

